trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.12.2'
  displayName: 'Install node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
  displayName: 'Set up JDK 11'

- task: DownloadSecureFile@1
  name: keystoreFile
  inputs:
    secureFile: 'debug.keystore'
  displayName: 'Download Keystore File'

- script: |
    mkdir %USERPROFILE%\.android
    move %AGENT_TEMPDIRECTORY%\debug.keystore %USERPROFILE%\.android\debug.keystore
  displayName: 'Move Keystore to Home Directory'
  condition: eq(variables['Agent.OS'], 'Windows_NT')

- script: |
    cd android
    gradlew.bat assembleRelease -PMYAPP_RELEASE_STORE_FILE=%USERPROFILE%\.android\debug.keystore -PMYAPP_RELEASE_KEY_ALIAS=%MYAPP_RELEASE_KEY_ALIAS% -PMYAPP_RELEASE_STORE_PASSWORD=%MYAPP_RELEASE_STORE_PASSWORD% -PMYAPP_RELEASE_KEY_PASSWORD=%MYAPP_RELEASE_KEY_PASSWORD%
  displayName: 'Build Android (Windows)'
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  env:
    JAVA_HOME: $(JAVA_HOME)
    ANDROID_HOME: $(ANDROID_HOME)
    MYAPP_RELEASE_STORE_FILE: $(MYAPP_RELEASE_STORE_FILE)
    MYAPP_RELEASE_KEY_ALIAS: $(MYAPP_RELEASE_KEY_ALIAS)
    MYAPP_RELEASE_STORE_PASSWORD: $(MYAPP_RELEASE_STORE_PASSWORD)
    MYAPP_RELEASE_KEY_PASSWORD: $(MYAPP_RELEASE_KEY_PASSWORD)

- script: |
    cd android
    gradlew.bat bundleRelease -PMYAPP_RELEASE_STORE_FILE=%USERPROFILE%\.android\debug.keystore -PMYAPP_RELEASE_KEY_ALIAS=%MYAPP_RELEASE_KEY_ALIAS% -PMYAPP_RELEASE_STORE_PASSWORD=%MYAPP_RELEASE_STORE_PASSWORD% -PMYAPP_RELEASE_KEY_PASSWORD=%MYAPP_RELEASE_KEY_PASSWORD%
  displayName: 'Build Android AAB (Windows)'
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  env:
    JAVA_HOME: $(JAVA_HOME)
    ANDROID_HOME: $(ANDROID_HOME)
    MYAPP_RELEASE_STORE_FILE: $(MYAPP_RELEASE_STORE_FILE)
    MYAPP_RELEASE_KEY_ALIAS: $(MYAPP_RELEASE_KEY_ALIAS)
    MYAPP_RELEASE_STORE_PASSWORD: $(MYAPP_RELEASE_STORE_PASSWORD)
    MYAPP_RELEASE_KEY_PASSWORD: $(MYAPP_RELEASE_KEY_PASSWORD)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/android/app/build/outputs/bundle/release'
    artifactName: 'aab'
  displayName: 'Publish AAB'
