# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.12.2'
  displayName: 'Install node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- task: DownloadSecureFile@1
  name: keystoreFile
  inputs:
    secureFile: 'debug.keystore'
  displayName: 'Download Keystore File'

- script: |
    mkdir -p $HOME/.android
    mv $(Agent.TempDirectory)/debug.keystore $HOME/.android/debug.keystore
  displayName: 'Move Keystore to Home Directory'
  condition: or( eq(variables['Agent.OS'], 'Linux'), eq(variables['Agent.OS'], 'Darwin'))

- script: |
    mkdir %USERPROFILE%\.android
    move %AGENT_TEMPDIRECTORY%\debug.keystore %USERPROFILE%\.android\debug.keystore
  displayName: 'Move Keystore to Home Directory'
  condition: eq(variables['Agent.OS'], 'Windows_NT')

- script: |
    cd android
    gradlew.bat assembleRelease -PMYAPP_RELEASE_STORE_FILE=%USERPROFILE%\.android\debug.keystore -PMYAPP_RELEASE_KEY_ALIAS=%MYAPP_RELEASE_KEY_ALIAS% -PMYAPP_RELEASE_STORE_PASSWORD=%MYAPP_RELEASE_STORE_PASSWORD% -PMYAPP_RELEASE_KEY_PASSWORD=%MYAPP_RELEASE_KEY_PASSWORD%
  displayName: 'Build Android (Windows)'
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  env:
    JAVA_HOME: '/path/to/java11' # Ensure this points to your Java 11 installation
    ANDROID_HOME: '/path/to/android/sdk'

- script: |
    cd android
    gradlew.bat bundleRelease -PMYAPP_RELEASE_STORE_FILE=%USERPROFILE%\.android\debug.keystore -PMYAPP_RELEASE_KEY_ALIAS=%MYAPP_RELEASE_KEY_ALIAS% -PMYAPP_RELEASE_STORE_PASSWORD=%MYAPP_RELEASE_STORE_PASSWORD% -PMYAPP_RELEASE_KEY_PASSWORD=%MYAPP_RELEASE_KEY_PASSWORD%
  displayName: 'Build Android AAB (Windows)'
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  env:
    JAVA_HOME: '/path/to/java11' # Ensure this points to your Java 11 installation
    ANDROID_HOME: '/path/to/android/sdk'

# - script: |
#     cd android
#     ./gradlew bundleRelease -PMYAPP_RELEASE_STORE_FILE=$HOME/.android/debug.keystore -PMYAPP_RELEASE_KEY_ALIAS=$(MYAPP_RELEASE_KEY_ALIAS) -PMYAPP_RELEASE_STORE_PASSWORD=$(MYAPP_RELEASE_STORE_PASSWORD) -PMYAPP_RELEASE_KEY_PASSWORD=$(MYAPP_RELEASE_KEY_PASSWORD)
#   displayName: 'Build Android AAB (Unix)'
#   condition: eq(variables['Agent.OS'], 'Linux') || eq(variables['Agent.OS'], 'Darwin')

# - script: |
#     cd android
#     gradlew.bat bundleRelease
#   displayName: 'Build Android AAB (Windows)'
#   condition: eq(variables['Agent.OS'], 'Windows_NT')

# - script: |
#     cd android
#     ./gradlew assembleRelease
#   displayName: 'Build Android (Unix)'
#   condition: eq(variables['Agent.OS'], 'Linux')

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/android/app/build/outputs/bundle/release'
    artifactName: 'aab'
  displayName: 'Publish AAB'
